### PR TITLE
Move server integration tests out of build target

### PR DESCRIPTION
**Pull request by cgtz**
* Changes to gradle config to only run unit tests when running `./gradlew build`
* `./gradlew test` now also runs tests in the `integration-test` directory
* Moved server tests to `integration-test` directory

Fixes issue #302 

Previously the end to end server tests were slowing down the build speed, so now they will only run when the `test` target is executed independently.  Other long-running tests can be moved to an `integration-test` directory as needed.

**Primary reviewers:** Priyesh, Gopal
**Time to review:** 5 min.

### CODE REVIEW

**Comment by pnarayanan** [comment]
This is very useful. Please also integrate the changes from #318 so that stack trace gets printed on error for tests in both `test` and `unitTest` tasks.

**Comment by cgtz** [comment]
I just added the stack trace printing changes

**Comment by pnarayanan** [comment]
Verified that `build` builds and runs unit tests and `test` runs the unit tests as well as the integration tests.

**Comment by pnarayanan** [comment]
LGTM

**Comment by vgkholla** [comment]
Checked out and tried it and it works. Builds are super fast !

Before I merge, I want to understand the changes in the gradle file. Will talk with @cgtz and merge.

**Pull request merged**
