### PR TITLE
Fixing a serialization length compute calculation

### PR DESCRIPTION
**Pull request by vgkholla**
Built and formatted.

### CODE REVIEW

**Comment by pnarayanan** [comment]
Change looks good. As an orthogonal point, I see no harm in supporting Unicode by serializing/deserializing in UTF8, only benefits.

**Comment by vgkholla** [comment]
@pnarayanan fair enough. let's discuss this and make the change. It should be minor but I want to see if we can write specific tests for verifying the flow. I don't want to do it in this change because this is addressing a correctness problem (i.e. the allocated space for the serialized key was its string length rather than the length of its byte representation)

**Comment by vgkholla** [comment]
Also need to verify if Netty supports non ASCII headers when it encodes and decodes.

**Comment by pnarayanan** [comment]
It is straightforward to test this manually, so a unit test would be simple enough to write if can we make the change.

**Comment by pnarayanan** [comment]
LGTM

**Pull request merged**
