### PR TITLE
make metrics reporter configurable

### PR DESCRIPTION
**Pull request by heipacker**
make metrics reporter configurable, not just JmxReporter

### CODE REVIEW

**Comment by vgkholla** [comment]
@heipacker Could you please describe a use case that needs this? I.e what other reporters do you plan to use and does this need to be done via configuration? The code looks a tad too involved and I want to see if there is some other way to achieve the same effect if this is really required.

Also, you will need to make the same changes to the server if we decide this required (the current changes are only for the frontend)

**Comment by heipacker** [comment]
I want sent  metrics to my monitor system by graphiteReporter, so I want make this configurable.
the last problem, my be is my pan

**Comment by vgkholla** [comment]
@heipacker ok I understand the use case - I suggest a different approach to solving your problem. Write a new "main" class (i.e. like `RestServerMain` or `AmbryFrontendMain` or `AmbryMain`) - all these "main" classes pass in the `ClusterMap` which means the `MetricRegistry` has already been created. You can do a `clusterMap.getMetricRegistry()` and attach it to whatever reporter you want. This requires no changes to the Ambry code base - you will just have to write a different main class for your application.

I have attached two gists that show how to do this (look for the line that says "// TODO: initialize required reporters here.")

[AmbryMain](https://gist.github.com/vgkholla/fffb19d1e701db77cd3284e76ee0e842#file-ambrymainnewreporter-txt-L31)
[RestServerMain](https://gist.github.com/vgkholla/8d83ebb760c7d0288b7d7c1d3f13709f#file-restservermainnewreporter-txt-L31)

You need not check in that code to the repository - it is for your application's use case only. I believe this solution is much cleaner and does not have the assumptions you make in this PR - that every reporter will have a `forRegistry()` and `start()` and `stop()` methods.

**Comment by vgkholla** [comment]
@heipacker I'm going to close this PR. The approach I have suggested should work for your use case.

**Pull request closed without merging**
