### PR TITLE
Upgrade netty and azure libraries

### PR DESCRIPTION
**Pull request by snalli**
Upgrade netty and azure libraries as per Microsoft recommendation

### CODE REVIEW

**Comment by snalli** [comment]
Wait for closed-source to deploy before merging

**Review by SophieGuo410 — APPROVED** [review]

**Comment by snalli** [comment]
Wait for closed-source to deploy before merging

**Comment by snalli** [comment]
Latest netty causing spiky latencies for GET

**Comment by snalli** [comment]
Investigated latency spikes. There are not due to netty upgrades

**Pull request merged**
