### PR TITLE
Use SslFactory to simplify BlockingChannelConnectionPool and related …

### PR DESCRIPTION
**Pull request by xiahome**
BlockingChannelConnectionPool used SslConfig and SslSocketFacotory to establish an Ssl connection. This patch simplifies the process by passing in SslFactory. This patch also makes corresponding changes in all related tests.

Test done: ./gradlew build

Reviewer: Priyesh & Siva

### CODE REVIEW

**Comment by pnarayanan** [comment]
Blocking channels are used by the coordinator today which is going to go away. The router does everything through the selector. Although this is not a sweeping change and is nice to have, it is better not to make any changes to the coordinator and worry about any regressions and such at this time. What do you think?

**Comment by pnarayanan** [comment]
Oh, and replication as well actually. Still not very inclined to have this change now. Let us discuss this.

**Comment by sriramsub** [comment]
My vote would be to not do this given that we want to eventually remove blocking semantics.

**Comment by xiahome** [comment]
Will take your call and drop this PR.

**Pull request closed without merging**
