### PR TITLE
[named blobs] implement list API

### PR DESCRIPTION
**Pull request by cgtz**
Implement a REST API on the frontend for listing blobs in a container
that start with a given prefix.

Add utilities that can be used to deserialize the JSON response in
client implementations.

### CODE REVIEW

**Review by SophieGuo410 — APPROVED** [review]
LGTM!

**Comment by zzmao** [comment]
Hi @cgetz Is there an example for the page token & nextContinuationToken?

**Comment by cgtz** [comment]
> Hi @cgetz Is there an example for the page token & nextContinuationToken?

Hi @zzmao, here is an example (I will add this to the design doc).

First, one may search for all the blobs that start with "foo/1.1/". Let's assume that the max number of elements to return per page is set to 2.

```
GET /named/acct/cont?prefix=foo%2F1.1%2F
{
  “entries”: [
    { “blobName”: “foo/1.1/bar”, “expirationTimeMs": 25 },
    { “blobName”: “foo/1.1/biz”}
  ],
  “nextPageToken”: “foo/1.1/blah”
}
```

The nextPageToken is a string that points to the start of the next page of results. For our mysql implementation, this is just the next key that starts with the prefix "foo/1.1/" since names are sorted. To continue reading the next page, you can make the following request:
```
GET /named/acct/cont?prefix=foo%2F1.1%2F&page=foo%2F1.1%2Fblah
{
  “entries”: [
    { “blobName”: “foo/1.1/blah”},
    { “blobName”: “foo/1.1/x”}
  ],
}
```

Since the response does not contain "nextPageToken", it indicates that there are no additional pages of blobs that start with foo/1.1/

**Review by zzmao — APPROVED** [review]
LGTM.

**Pull request merged**
