### PR TITLE
Moving changes from ambry-frontend to ambry-admin

### PR DESCRIPTION
**Pull request by vgkholla**
Development of V1 of `ambry-frontend` is now finished. This is a good juncture to bring the admin code up to speed so that development of useful administration/operations APIs can commence.

This commit has almost nothing to review since the code from `ambry-frontend` has been simply copied into `ambry-admin` with renames of classes and variables. It should be good to merge right away.

The next steps will be to:
1. Plug in the `GetReplicasForBlobId` API so that it works for the Admin.
2. Remove POST API support from the Admin.
3. Remove redundant APIs (GET UserMetadata for e.g).

After that, the development of admin APIs can start.

Built and formatted. Unit test coverage is same as `ambry-frontend`.

### CODE REVIEW

**Comment by sriramsub** [comment]
do we really need all the frontend stuff for admin?

**Comment by vgkholla** [comment]
No we don't - I'm going to start taking out code that isn't required. It's a straight copy now to make it easy to merge now and then review the removals later on. If I remove in this change, it will be hard to review them.

**Comment by vgkholla** [comment]
Also, other than POST, GET UserMetadata and maybe HEAD, I don't see what else can be removed.

GET of blobs, GET BlobInfo and DELETE are still useful.

**Comment by vgkholla** [comment]
According to me most of the differences with the frontend will lie in the APIs, headers that allow you to get deleted/expired blobs, deletes with accounting details - basically a lot of changes that will go into `AdminSecurityService`.

**Pull request merged**
