### PR TITLE
Support adding BlobStore to StorageManager

### PR DESCRIPTION
**Pull request by johnnyjian**
The first step to support dynamically adding partition/replica.

The plan is to support adding partition/replica to StorageManager, ReplicationManager and StatsManager, and finally add a PartitionWatcher to watch changes of partitions on cluster map, and call these add methods.

### CODE REVIEW

**Comment by jsjtzyy** [comment]
@johnnyjian Can you publish a document to describe (1) your use case, motivation; (2) how you want to make changes (i.e. the logical workflow, what components you will touch and implementation approach); (3)  TODO list/ future plan and potential challenges etc. 
 
Since internally we also plan to work on this part, a detailed document will help us discuss it and avoid unnecessary misunderstandings.

Thanks in advance.

**Comment by johnnyjian** [comment]
@jsjtzyy OK, I will write a document, but need some time.

**Comment by jsjtzyy** [comment]
@johnnyjian Thank you Johnny!  Let's keep in touch and make sure we are always on the same page.

**Comment by jsjtzyy** [comment]
@johnnyjian  Hi Johnny, we have a initial design for "move" Blobstore (both addition/deletion). Feel free to access the following link and leave comments: https://docs.google.com/document/d/1P1CEQV5nZa99BKv-f5rYT9mmUIQHbQ436w9ayK8ABow/edit

It's still a rough version. We will keep updating it and finalize the design in a couple of weeks. 
Thanks.

**Comment by jsjtzyy** [comment]
@johnnyjian we have a tentative plan to "move" replica which you might be interested in. 
https://docs.google.com/document/d/1P1SnTQ-1WvsLkPmHwmSGJeIHoxGov-hT49tFCnrlg2g/edit
Any suggestions will be highly appreciated.

**Comment by jsjtzyy** [comment]
After internal discussion, we almost reach consensus on design of move/add/remove replica dynamically. Here is the finalized high level design: https://docs.google.com/document/d/1wbezmElua914JTEBxxjfEwGDDnXfYq20xZcdwwTSbpg/edit

The implementation may need a couple of months. Feel free to leave comments.

**Comment by jsjtzyy** [comment]
@johnnyjian  PRs #1232 #1226 implement logic of adding / removing store in StorageManager. Will close this PR. Feel free to create issues and let us know if you have any suggestions/questions. Thanks!

**Pull request closed without merging**
